### ISSUE TITLE
change resolution of highway=track similar to highway=minor/unclassified 

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#29]
At low zoom levels, track is more visible than minor and unclassified.  Adjust track to a similar resolution level of minor/unclassified or even higher.

**Comment by maning** [comment]
@ralleon, do you think this is a good change?

**Comment by ralleon** [comment]
sorry for late reply. my pc crashed (sobrang puno na) i deleted some things
that were not supposed to be deleted. :-)

Anyway, I specifically adjusted the resolution of roads particularly the
unpaved barangay roads that are considered major links in between sitios or
far flung villages.

Logic:
Why? When we go to mountain villages, chances are we are not tourists or
doing so for recreation. There's always a possibility that unpaved roads
earlier plotted may have been cemented, asphalted or becomes worse (almost
unpassable). We don't know unless we visit them again after many years.

So, we use gps not to autoroute to that place, but to 'give us an idea of
our optional routes' (whether it's unpaved, 4x4 trail, private road (with
tolerance from owner), etc) depending on the capability of our vehicles. We
view all these roads 'zoomed out'. If the roads disappear on your small
mobile screen, then they will not serve their purpose. (If you just
autoroute, it will give you the only good road, not the other alternate
roads. Gets?).

Side effects:
tagging in osmph is not defined very well by the community 'as to its
purpose'. All unpaved road seem to be considered unessential roads. In PH,
most barangay roads are still unpaved (compacted) or even slippery to almost
impassable to smaller vehicles... in my opinion, should be at the very
least, a tertiary road (collector road). But since we can't tag it as that,
the least I can do is render it at lower zoom level

Like How do you represent roads leading to remote villages in Tanay, eg.
Sta. Ines or Tinukan? If we let them disappear on map, how can the rescuer
look for the essential roads (in case of planning rescue efforts, or
rerouting if the rescue team found that the road is impassble). They must
have the capability to pan left and right for alternatives...

You can't expect 4x4 users or roadhikers to zoom-in just to see their roads.
There's no point since there are no other POI's or landmarks in the
mountain. What they are looking for, are polygons to get their bearings &
know their general directions (eg. mountains, body of water and other
natural obtructions) that can only be viewed while zoomed out.

---

Or we may need to add more tags:
highway=track
essential=yes (or something like that) --- so that only essential mountain
roads or barangay roads are rendered together with all other tertiaries.

## only residential roads need not be seen while zoomed out.

highway=residential
surface=unpaved

Other solution:
produce 2 version of maps (for recreation & for rescue/humanitarian),

**Comment by maning** [comment]
OK, given your justification, I will revert the changes.  Funny how
just two characters are affected for such a long response. :)

On Fri, Jul 1, 2011 at 1:45 PM, ralleon
reply@reply.github.com
wrote:

> sorry for late reply. my pc crashed (sobrang puno na) i deleted some things
> that were not supposed to be deleted. :-)
> 
> Anyway, I specifically adjusted the resolution of roads particularly the
> unpaved barangay roads that are considered major links in between sitios or
> far flung villages.
> 
> Logic:
> Why? When we go to mountain villages, chances are we are not tourists or
> doing so for recreation. There's always a possibility that unpaved roads
> earlier plotted may have been cemented, asphalted or becomes worse (almost
> unpassable). We don't know unless we visit them again after many years.
> 
> So, we use gps not to autoroute to that place, but to 'give us an idea of
> our optional routes' (whether it's unpaved, 4x4 trail, private road (with
> tolerance from owner), etc) depending on the capability of our vehicles. We
> view all these roads 'zoomed out'. If the roads disappear on your small
> mobile screen, then they will not serve their purpose. (If you just
> autoroute, it will give you the only good road, not the other alternate
> roads. Gets?).
> 
> Side effects:
> tagging in osmph is not defined very well by the community 'as to its
> purpose'. All unpaved road seem to be considered unessential roads. In PH,
> most barangay roads are still unpaved (compacted) or even slippery to almost
> impassable to smaller vehicles... in my opinion, should be at the very
> least, a tertiary road (collector road). But since we can't tag it as that,
> the least I can do is render it at lower zoom level
> 
> Like How do you represent roads leading to remote villages in Tanay, eg.
> Sta. Ines or Tinukan? If we let them disappear on map, how can the rescuer
> look for the essential roads (in case of planning rescue efforts, or
> rerouting if the rescue team found that the road is impassble). They must
> have the capability to pan left and right for alternatives...
> 
> You can't expect 4x4 users or roadhikers to zoom-in just to see their roads.
> There's no point since there are no other POI's or landmarks in the
> mountain. What they are looking for, are polygons to get their bearings &
> know their general directions (eg. mountains, body of water and other
> natural obtructions) that can only be viewed while zoomed out.
> 
> ---
> 
> Or we may need to add more tags:
> highway=track
> essential=yes (or something like that) --- so that only essential mountain
> roads or barangay roads are rendered together with all other tertiaries.
> 
> ## only residential roads need not be seen while zoomed out.
> 
> highway=residential
> surface=unpaved
> 
> Other solution:
> produce 2 version of maps (for recreation & for rescue/humanitarian),
> 
> On Fri, Jul 1, 2011 at 10:56 AM, maning <
> reply@reply.github.com>wrote:
> 
> > @ralleon, do you think this is a good change?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/maning/osmphgps/issues/29#issuecomment-1480454
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maning/osmphgps/issues/29#issuecomment-1480869

## 

cheers,

## maning

"Freedom is still the most radical idea of all" -N.Branden
wiki: http://esambale.wikispaces.com/

## blog: http://epsg4253.wordpress.com/
