### ISSUE TITLE
too much noise for street/address search results

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#34]
On Thu, Jul 7, 2011 at 3:39 PM, Jun Martin

> Yes, I tried Saint John and Saint John Street, the first one has no
> matches (but there is a Saint John).  Same thing for Saint Luke and
> Saint Luke Street.
> 
> On 7/7/2011 3:30 PM, maning sambale wrote:
> 
> > Just tried "Sampaloc Road" and I can find it.  But you're right some
> > streets have names but when you tapped them (e.g. Sampaloc), the "No
> > Matches Found" appear.

**Comment by ralleon** [comment]
Without mkgmap-locator and without address tags on roads, what's the basis
of mkgmap r1867 to assign road's address to specific town or city?
Most probably, the roads are associated by mkgmap to a city, if they fall
within a certain radius from the nearest city-poi. This becomes a
complicated issue with irregular shaped city boundaries in NCR.

Or is it possible that if a road is very far from city-POI (outside a given
radius), it's not indexed, thus cannot be searched? just a guess.

**Comment by maning** [comment]
Just to add to your guess, I think regardless of what you specify as your City, street search gives out all the possible streets in your specified query that is contained within the tile.  However, when you tap on each street name, the only valid street within the city will show a match.  

Moreover, if the place node is on another tile, you can't get any match at all. :(

**Comment by ralleon** [comment]
"the only valid street within the city will show a match"
---but assuming the shape of a city-A is long and narrow (eg. like a leech),
and it's city-POI is located on the center of its polygon, the streets at
its far end will become nearer to adjacent city-POI of a nearby City-B. In
which case, without a locator, that far-end streets will become associated
to City-B during the indexing (due to nearer radius proximity)

On address search, if you type City-A, then look for that said streets,
chances are you'll get a blank result (no match). Maybe this is what's
happening.

**Comment by maning** [comment]
Seems to be fixed with the mkgmap-city-region-index-r1992. Will wait for more reports before closing this issue.
