### ISSUE TITLE
6 san fernando's are missing on your current compiler version

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#9]
The latest OSMPH-Garmin (20110311, mkgmap index v1860) has only one San Fernando (from Bukidnon)

Can you try using mkgmap r1867?

Our OSM beta (compiled on mkgmap r1867) has at least 7 San Fernando in city seach result from provinces of: Bukidnon, Camarines Sur, Cebu, La Union, Masbate, Pampanga, Romblon.

**Comment by maning** [comment]
Is this problem appears only with San Fernando or other towns/cities as well?

**Comment by maning** [comment]
Using Mac RoadTrip (V 2.0.2) and BaseCamp (V. 3.1.2) `Search Cities`, I can find all `San Fernando` (towns/cities).

Using Mapsource (V. 6.11.6), under the `Find Places`, I search for `San Fernando` gives 1 result in Bukidnon.  Using the `Find Nearest Places` > `Cities`, all `San Fernando` are found.

**Comment by maning** [comment]
Using nuvi 1310, only `San Fernando, Bukidnon, PHL` is avalaibale in the `City` search.

**Comment by maning** [comment]
Confirmed that all San Fernando's are searcheable with mkgmap r1867

**Comment by maning** [comment]
related discussion in the mkmap-dev list: http://www.mkgmap.org.uk/pipermail/mkgmap-dev/2011q2/011620.html

**Comment by maning** [comment]
Compiled using the mkgmap-city-region-index-r1992.  @ralleon, please test.

**Comment by ralleon** [comment]
http://dl.dropbox.com/u/607635/osm-ph_gps_maps/dev/osmph_winmapsource_latest_dev.exe

on quick testing, all San Fernando's appear on city-search on Nuvi 1310,
yehey.

address search is working on Nuvi 1310 (no more annoying 'no map data
available'. nice :-)

possible bug: the museum & historical category on Nuvi1310 returns Sitios
and Subdivisions.

Will do further testing later... medyo busy lang today. I'll give you an
update tomorrow. excited.... :-)

**Comment by ralleon** [comment]
I compiled using my beta style under the latest
mkgmap-city-region-index-r1992, with same result on nuvi1310:
-no problem with similarly-named cities
-working address search
-same problem with Museum category on nuvi 1310 ---- it returns subdivision
and villages instead of museum. I guess it's just a minor style adjustment &
hex reassignment. I'll investigate that later.

We just need confirmations from users of nuvi 760 14xx 12xx Oregon if they
have no problem with San Fernando's and Address Search

We are almost there! :-)
(I can return your nuvi 1310 later, no further testing needed)

**Comment by maning** [comment]
OK, great news!  We can perhaps send a message to the beta testers.
And then squash a few issues (minor hex assigns and typ) then public
release?
